name: Check Workflows
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        * * * * *
    - cron: "0 0 * * *"

jobs:
  # check-validate:
    # name: Validate
    # uses: ./.github/workflows/validate.yml

  # check-linux:
    # name: Linux
    # uses: ./.github/workflows/spm-linux.yml

  # check-macos:
    # name: macOS
    # uses: ./.github/workflows/spm-macos.yml

  # check-windows:
    # name: Windows
    # uses: ./.github/workflows/spm-windows.yml

  # check-wasm:
    # name: Wasm
    # uses: ./.github/workflows/spm-wasm.yml

  check-ios:
    name: iOS
    uses: ./.github/workflows/xcodebuild.yml
    with:
      target_platform: iOS

  check-tvOS:
    name: tvOS
    uses: ./.github/workflows/xcodebuild.yml
    with:
      target_platform: tvOS
