name: Self Test Shared Actions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        * * * * *
    - cron: "0 0 * * *"

jobs:
  selftest-linux:
    name: Linux
    uses: ./.github/workflows/ci-linux.yml

  selftest-macos:
    name: macOS
    uses: ./.github/workflows/ci-macos.yml

  selftest-windows:
    name: Windows
    uses: ./.github/workflows/ci-windows.yml

  selftest-wasm:
    name: WASM
    uses: ./.github/workflows/ci-wasm.yml
