name: (i|tv)(Pad)OS

on:
  workflow_call:

jobs:
  ios-SPM:
    name: SPM ${{ matrix.destination }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config: # newer versions at top
          - { os: "macos-15", xcode: "16.0" }
          - { os: "macos-14", xcode: "15.4" }
        destination:
          - iOS
          - tvOS
        build_config:
          - Debug
          - Release
    steps:
      - uses: actions/checkout@v4

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: ${{ runner.os }}-spm-xcode-${{ hashFiles('Package.resolved', '**/*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode-

      - name: Select Xcode ${{ matrix.config.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.config.xcode }}.app

      - name: Build for Any ${{ matrix.destination }} Device
        run: |
          xcodebuild -scheme "shared-actions-Package" -configuration ${{ matrix.build_config }} -destination "generic/platform=${{ matrix.destination }},name=Any ${{ matrix.destination }} Device" build

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-swift_${{ matrix.config.xcode }}-${{ matrix.destination }}-${{ matrix.build_config }}-${{ github.run_id }}
          path: |
            ~/Library/Developer/Xcode/DerivedData/
          if-no-files-found: warn
          include-hidden-files: true
