name: Linux

on:
  workflow_call:
    inputs:
      swift_build_dir:
        type: string
        description: "Specify a custom build directory path (default .build)"
        default: ".build"
      spm_cache_dir:
        type: string
        description: "Specify a custom SPM cache directory path (default ~/Library/Caches/org.swift.swiftpm)"
        default: "~/Library/Caches/org.swift.swiftpm"

jobs:
  Linux-SPM:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: # https://hub.docker.com/_/swift/tags
          - "latest"
          - "5.10.1"
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/org.swift.swiftpm
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          swift build -c debug
          swift build -c release

      - name: Test
        run: |
          swift test -c debug
          swift test -c release

      - name: Run
        run: |
          swift run -c debug shared-actions
          swift run -c release shared-actions

      - name: <Debug>
        run: |
          swift --version
          ls -la .
          ls -la .build
          ls -la ~/.cache/org.swift.swiftpm
          exit(-1) # Simulate failure

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-${{ github.run_id }}
          path: |
            .build/*.yaml
            .build/*.xml
            .build/*.json
            .build/*.txt
            .build/[debug|release]/*.xctest
            .build/[debug|release]/*.json
            .build/[debug|release]/*.txt
          if-no-files-found: warn
          include-hidden-files: true
