name: macOS

on:
  workflow_call:

jobs:
  macos-SPM:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - { os: "macos-14", xcode: "15.4" }
          - { os: "macos-15", xcode: "16.0" }
    steps:
      - uses: actions/checkout@v4

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved', '**/*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Select Xcode ${{ matrix.config.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.config.xcode }}.app

      - name: Build
        run: |
          swift build -c debug
          swift build -c release

      - name: Test
        run: |
          swift test -c debug
          swift test -c release

      - name: Run
        run: |
          swift run -c debug shared-actions
          swift run -c release shared-actions

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-swift_${{ matrix.config.xcode }}-${{ github.run_id }}
          path: |
            .build
          if-no-files-found: warn
          include-hidden-files: true
