name: WASM

on:
  workflow_call:

jobs:
  wasm:
    runs-on: ubuntu-latest
    container: swift:6.0.3
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v2
      - run: swift build --swift-sdk wasm32-unknown-wasi
