name: WASM

on:
  workflow_call:

jobs:
  WASM-SPM:
    name: SPM Wasm
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_config:
          - debug
          - release
    container:
      image: ghcr.io/swiftwasm/carton:latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/org.swift.swiftpm
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          swift build -c ${{ matrix.build_config }}

      - name: Test
        run: |
          carton test -c ${{ matrix.build_config }}

      - name: Run
        run: |
          swift run -c ${{ matrix.build_config }} shared-actions

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-${{ matrix.build_config }}-${{ github.run_id }}
          path: |
            .build
          if-no-files-found: warn
          include-hidden-files: true
