name: Check markdown links

on:
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.16

