name: Linux

on:
  workflow_call:
    inputs:
      swift_build_dir:
        type: string
        description: "Specify a custom build directory path (default .build)"
        default: ".build"
      spm_cache_dir:
        type: string
        description: "Specify a custom SPM cache directory path (default ~/Library/Caches/org.swift.swiftpm)"
        default: "~/Library/Caches/org.swift.swiftpm"

jobs:
  SPM-Linux:
    name: SPM Linux Swift ${{ matrix.swift_version }} [${{ matrix.build_config }}]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        swift_version: # https://hub.docker.com/_/swift/tags
          - "latest"
          - "5.10.1"
        build_config:
          - debug
          - release
    container:
      image: swift:${{ matrix.swift_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/org.swift.swiftpm
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          swift build -c ${{ matrix.build_config }}

      - name: Test
        run: |
          swift test -c ${{ matrix.build_config }}

      - name: Run
        run: |
          swift run -c ${{ matrix.build_config }} shared-actions

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-swift_${{ matrix.swift_version }}-${{ matrix.build_config }}-${{ github.run_id }}
          path: |
            .build
          if-no-files-found: warn
          include-hidden-files: true
